services:
  vms_app:
    build: .
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    restart: always  # Ensures that the container always restarts

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/ssl/certs:ro
      - ./nginx/certs:/etc/ssl/private:ro
    depends_on:
      - vms_app
    restart: always  # Ensures the Nginx container always restarts
